#
#  $Header: /u/gcmpack/MITgcm_contrib/atnguyen/llc_270/aste_270x450x180/code_ad/packages.conf,v 1.1 2014/01/14 07:09:16 atn Exp $
#  $Name:  $
#

gfd
-mom_fluxform
exch2
cal
exf
gmredi
kpp
diagnostics
obcs
debug
seaice
#profiles
#mnc
#tides
